name: Ejercicio05

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest, alpine-latest]    
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Sistema Operativo        
        run: echo "S. O.:${{ runner.os }}!"
      - name: Recursos Hardware
        run: cat /proc/cpuinfo | grep “model name”
      - name: IP
        run: ip add
