name: Ejercicio04
on:
  push:
    branches:
      - main
jobs:
  crear-acceder-contenedor:
    runs-on: ubuntu-latest
    services:
      portal:
        image: httpd:latest
        ports:
          - 8080:80
    steps:
     - name: Acceder al Portal
       uses: curl http://localhost:8080
