name: Ejercicio03
on:
  push:
    branches:
      - main
jobs:
  configuracion:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout script configuracion
       uses: actions/checkout@v2
     - name: Ejecutamos script configuracion
       run: sh ./configuracion.sh
  construccion:
    needs: configuracion
    runs-on: ubuntu-latest
    steps:
     - name: Checkout script construccion
       uses: actions/checkout@v2
     - name: Ejecutamos script construccion
       run: sh ./construccion.sh
  prueba01:
    needs: construccion
    runs-on: ubuntu-latest
    steps:
     - name: Checkout script prueba
       uses: actions/checkout@v2
     - name: Ejecutamos script prueba
       run: sh ./prueba.sh
  prueba02:
    needs: construccion
    runs-on: ubuntu-latest
    steps:
     - name: Checkout script prueba
       uses: actions/checkout@v2
     - name: Ejecutamos script prueba
       run: sh ./prueba.sh
  despliegue:
    needs: [prueba01, prueba02]
    runs-on: ubuntu-latest
    steps:
     - name: Checkout script prueba
       uses: actions/checkout@v2
     - name: Ejecutamos script prueba
       run: sh ./despliegue.sh
