name: Ejercicio05

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest, alpine-latest]    
    steps:
      - name: Sistema Operativo        
        run: lsb_release -d
      - name: Recursos Hardware
        run: lscpu
      - name: IP
        run: ip add
