name: Ejercicio04
on:
  push:
    branches:
      - main
jobs:
  crear-acceder-contenedor:
    runs-on: ubuntu-latest
    services:
      portal:
        image: httpd:latest
        ports:
          - 8080:80
          
    steps:
     - name: Checkout hola.php
       uses: actions/checkout@v2
     - name: Copiamos hola.php a www
       run: cp hola.php ~/var/www
     - name: Acceder a hola.php
       run: curl http://localhost:8080/hola.php
