name: Ejercicio01
on:
  push:
    branches:
      - main
jobs:
  ejercicio01:
  runs-on: ubuntu:latest
  steps:
    - name: step01
      run: ls -la
    - name: step02
      run: date
    - name: step03
      run: df -h
      
